name: PoC 2
on: [workflow_dispatch]
jobs:
  bypass-firewall-with-rc:
    runs-on: ubuntu-latest
    steps:


      - uses: step-security/harden-runner@rc
        with:
          egress-policy: block
          disable-sudo: true
          allowed-endpoints: >
            github.com:443

      - name: Checkout
        uses: actions/checkout@v6

      - name: Test bypass
        run: |
          python3 http.py
