name: Cfnrelease

on:
  workflow_dispatch:
  

permissions: # added using https://github.com/step-security/secure-repo
  contents: read

jobs:
  publish-test:
    permissions:
      contents: read
      
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@rc
        with:
          egress-policy: audit
          
      - name: Checkout
        uses: actions/checkout@629c2de402a417ea7690ca6ce3f33229e27606a5
        with:
          fetch-depth: 0

      - name: Build, tag, and push image to Amazon ECR
        run: |
          docker build .
